version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - network_swarm_public
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=MudarSenha123!
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.seu-dominio.com.br`)
        - traefik.http.routers.rabbitmq.entrypoints=websecure
        - traefik.http.routers.rabbitmq.tls.certresolver=letsencryptresolver
        - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
        - traefik.http.routers.rabbitmq.service=rabbitmq
        # Middleware de Auth básico opcional para proteção extra do dashboard (descomente se desejar)
        # - traefik.http.routers.rabbitmq.middlewares=auth-rabbitmq
        # - traefik.http.middlewares.auth-rabbitmq.basicauth.users=admin:$$apr1$$...

volumes:
  rabbitmq_data:
    external: true
    name: rabbitmq_data

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
